services:
  - type: web
    name: getskilled-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: 5000
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: server_getskilled-main
    pythonVersion: 3.11.0
